# Generated by Django 3.0.2 on 2020-01-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='First Name',
            field=models.CharField(default='username_first', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='Last Name',
            field=models.CharField(default='username_last', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='Score',
            field=models.IntegerField(default=100),
        ),
    ]
