# Generated by Django 3.0.2 on 2020-02-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='solution_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
