# Generated by Django 3.0.2 on 2020-01-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200125_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Score',
            field=models.CharField(default='total_score', max_length=100),
        ),
    ]
