# Generated by Django 3.0.2 on 2020-02-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200201_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='solution_file',
            field=models.FileField(default=None, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
