# Generated by Django 3.0.2 on 2020-01-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200125_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Score',
        ),
    ]
