# Generated by Django 3.0.2 on 2020-01-26 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_member_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contest Name', models.CharField(default='contest_x', max_length=100)),
                ('Data path', models.CharField(default='/', max_length=100)),
                ('Max Score', models.IntegerField(default=100)),
                ('Contest Description', models.CharField(default='Empty', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='contribute',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('score', models.FloatField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Contest')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
