# Generated by Django 3.0.2 on 2020-01-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200126_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='Data require',
            field=models.BooleanField(default=True),
        ),
    ]
