# Generated by Django 3.0.2 on 2020-01-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contest_data require'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='Data path',
            new_name='data_path',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='Data require',
            new_name='data_require',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='Contest Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='Max Score',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='Contest Name',
            new_name='name',
        ),
    ]
