# Generated by Django 3.0.2 on 2020-01-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200126_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='represent_image',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
