# Generated by Django 3.0.2 on 2020-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contest_represent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='file_name', max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
