# Generated by Django 3.0.2 on 2020-01-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
