# Generated by Django 3.0.2 on 2020-01-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_filemodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='datetime',
            field=models.DateField(null=True),
        ),
    ]
