# Generated by Django 3.0.2 on 2020-01-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200129_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='rank',
        ),
    ]
